"""Regenerate the outlined lockup from a font.

    uv run --with fonttools python tools/build-lockup.py

A wordmark that ships as live text falls back silently: the reader who lacks the font
gets whatever their system offers, and the lockup is no longer the lockup. Outlining it
fixes that, and outlining it *from a script* keeps the decision auditable - the font,
the size and the tracking are read here rather than recovered from path data later.

The font must permit it. JetBrains Mono is under the SIL Open Font License, which allows
embedding and derivative works; the fonts Apple ships with macOS do not, so a mark
outlined from Menlo or SF Mono is a licensing problem that only surfaces once the project
is public.

The font is vendored under tools/fonts, with its licence, and its digest is checked before
a glyph is read. A generator that takes whatever font is installed produces a wordmark
that is wrong without looking wrong.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

FONT = Path(__file__).resolve().parent / "fonts" / "JetBrainsMono-Regular.ttf"
# JetBrains Mono 2.304, unmodified. See tools/fonts/README.md for where it came from.
FONT_SHA256 = "a0bf60ef0f83c5ed4d7a75d45838548b1f6873372dfac88f71804491898d138f"

WORD = "trysquare"
SIZE = 25.0  # px, against a mark 51px tall
TRACKING = 0.5  # px between glyphs

# The mark, placed in a 64px box by `translate(2 6) scale(0.8)`, and the extent of its own
# artwork inside that box. Everything else is derived from these, because a lockup that
# carries hand-tuned offsets drifts the moment either half changes.
MARK_SCALE = 0.8
MARK_DX, MARK_DY = 2.0, 6.0
MARK_X0, MARK_Y0, MARK_X1, MARK_Y1 = 7.6, 11.85, 56.4, 52.15

GAP_EM = 0.5  # space between mark and word, as a fraction of the type size

OUT = Path(__file__).resolve().parent.parent / "docs" / "_static" / "logo"

# Blade, stock, ink. The dark ground needs the blade inverted and the brass lifted a
# step, exactly as the mark does.
THEMES = {
    "light": {"blade": "#232B33", "stock": "#A97C2A", "ink": "#232B33"},
    "dark": {"blade": "#C9D3DB", "stock": "#C79338", "ink": "#C9D3DB"},
}

TEMPLATE = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} 64" \
width="{width}" height="64" role="img" aria-label="trysquare">
  <title>trysquare</title>
  <!-- Horizontal lockup for a {theme} ground, wordmark outlined. Generated by
       tools/build-lockup.py from {font} ({size}px, {tracking}px tracking) - edit the
       script, not the path data. The word carries no font dependency and cannot fall
       back silently. -->
  <g transform="translate({mark_dx} {mark_dy}) scale({mark_scale})">
    <g transform="translate(7.6 37.3) rotate(-45)">
      <path fill-rule="evenodd" fill="{blade}"
            d="M11.5 12 H48 V21 H11.5 Z
               M22 17 H23.6 V21 H22 Z
               M28 17 H29.6 V21 H28 Z
               M34 17 H35.6 V21 H34 Z
               M40 17 H41.6 V21 H40 Z" />
      <path fill="{stock}" d="M0 0 H12 V21 H0 Z" />
    </g>
  </g>
  <path fill="{ink}" transform="translate({text_x} {baseline}) scale({scale} -{scale})"
        d="{word}" />
</svg>
"""


def outline(word: str, font: TTFont) -> tuple[str, float]:
    """Return the word as one path in font units, and its advance in font units."""
    upem = font["head"].unitsPerEm
    glyph_set = font.getGlyphSet()
    cmap = font.getBestCmap()
    widths = font["hmtx"]
    tracking_units = TRACKING * upem / SIZE

    parts: list[str] = []
    x = 0.0
    for char in word:
        name = cmap[ord(char)]
        pen = SVGPathPen(glyph_set)
        glyph_set[name].draw(TransformPen(pen, (1, 0, 0, 1, x, 0)))
        commands = pen.getCommands()
        if commands:  # a space has no contour
            parts.append(commands)
        x += widths[name][0] + tracking_units

    return " ".join(parts), x - tracking_units


def main() -> None:
    if not FONT.exists():
        raise SystemExit(f"font not found: {FONT}")

    digest = hashlib.sha256(FONT.read_bytes()).hexdigest()
    if digest != FONT_SHA256:
        raise SystemExit(
            f"{FONT.name} is not the font this lockup was drawn with.\n"
            f"  expected {FONT_SHA256}\n"
            f"  found    {digest}\n"
            "Restore it, or update FONT_SHA256 and tools/fonts/README.md deliberately."
        )

    font = TTFont(FONT)
    upem = font["head"].unitsPerEm
    scale = SIZE / upem
    path, advance_units = outline(WORD, font)

    # "trysquare" is all lower case, so the eye centres it on the x-height band, not on
    # the em box. Aligning the mark's centre to the box centre leaves the mark visibly
    # floating above the word - so take the x-height from the font and align to that.
    x_height = font["OS/2"].sxHeight * scale
    mark_left = MARK_DX + MARK_X0 * MARK_SCALE
    mark_right = MARK_DX + MARK_X1 * MARK_SCALE
    mark_centre_y = MARK_DY + (MARK_Y0 + MARK_Y1) / 2 * MARK_SCALE

    text_x = mark_right + GAP_EM * SIZE
    baseline = mark_centre_y + x_height / 2
    # The right margin repeats the left one, so the pair reads as one object.
    width = round(text_x + advance_units * scale + mark_left)
    print(f"x-height {x_height:.2f}px  baseline {baseline:.2f}  word starts {text_x:.2f}")

    for theme, colours in THEMES.items():
        svg = TEMPLATE.format(
            width=width,
            theme=theme,
            font=FONT.name,
            size=SIZE,
            tracking=TRACKING,
            text_x=f"{text_x:.4g}",
            baseline=f"{baseline:.4g}",
            scale=f"{scale:.6g}",
            mark_dx=f"{MARK_DX:.4g}",
            mark_dy=f"{MARK_DY:.4g}",
            mark_scale=f"{MARK_SCALE:.4g}",
            word=path,
            **colours,
        )
        target = OUT / f"trysquare-lockup-{theme}.svg"
        target.write_text(svg, encoding="utf-8")
        print(f"{target.relative_to(OUT.parent.parent.parent)}  {width}x64")


if __name__ == "__main__":
    main()
